services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: code_review_db
      POSTGRES_USER: code_review_user
      POSTGRES_PASSWORD: code_review_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: code_review_db
      DB_USER: code_review_user
      DB_PASSWORD: code_review_pass
      DB_HOST: db
      DB_PORT: 5432
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      AI_MODEL: claude-sonnet-4-6
    depends_on:
      - db

volumes:
  postgres_data:
